version: '3.8'

services:
  api:
    # Ändra från 'build' till 'image' för att använda din nya GitHub-container
    image: ghcr.io/refactorninja12/minitrello:latest
    ports:
      - "8080:8080"
    environment:
      - Jwt__Key=${JWT_KEY}
      - ConnectionStrings__DefaultConnection=Host=db;Database=minitrellodatabase;Username=postgres;Password=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=minitrellodatabase
    ports:
      - "5433:5432"
    # Tips: Lägg till en volume så din data inte försvinner om containern dör
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: